### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by v1kb4t** [miyamotononno/gs_hackathon_2024#4]
## Nishimura-san
- [ ] Explore LLM API Options (GPT4 vs Gemini)
- [ ] Explore prompt engineering plus API usage
## Nozomu-san
- [ ] Explore LLM API Options (GPT4 vs Gemini)
- [ ] App deployment
## Nath
- [ ] Decide the PR, Issue of OS repo for demo
## Teki
- [ ] Explore JIRA, Github/Gitlab API for PR/MR files changed
